CREATE TABLE professeur (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            nom VARCHAR(255) NOT NULL,
                            prenom VARCHAR(255) NOT NULL,
                            specialite VARCHAR(255) NOT NULL
);