stages:
  - build
  - unit-tests
  - quality

build_backend:
  stage: build
  image: maven:3.8-openjdk-17
  script:
    - cd etudiant-service && mvn clean package -B
    - cd professeur-service && mvn clean package -B
    - cd cours-service && mvn clean package -B
    - cd emploi-du-temps-service && mvn clean package -B
  artifacts:
    paths:
      - etudiant-service/target/*.jar
      - professeur-service/target/*.jar
      - cours-service/target/*.jar
      - emploi-du-temps-service/target/*.jar
    expire_in: 1 week

unit_tests_backend:
  stage: unit-tests
  image: maven:3.8-openjdk-17
  script:
    - cd etudiant-service && mvn test
    - cd professeur-service && mvn test
    - cd cours-service && mvn test
    - cd emploi-du-temps-service && mvn test

quality_check:
  stage: quality
  image: maven:3.8-openjdk-17
  script:
    - cd etudiant-service && mvn sonar:sonar -Dsonar.login=$SONAR_TOKEN
    - cd professeur-service && mvn sonar:sonar -Dsonar.login=$SONAR_TOKEN
    - cd cours-service && mvn sonar:sonar -Dsonar.login=$SONAR_TOKEN
    - cd emploi-du-temps-service && mvn sonar:sonar -Dsonar.login=$SONAR_TOKEN
  dependencies:
    - build_backend
    - unit_tests_backend



