stages:
  - build
  - unit-tests

build_backend:
  stage: build
  image: maven:3.9-openjdk-22  # Changement ici
  script:
    - cd etudiant-service && mvn clean package -B
    - cd professeur-service && mvn clean package -B
    - cd cours-service && mvn clean package -B
    - cd emploi-du-temps-service && mvn clean package -B
  artifacts:
    paths:
      - etudiant-service/target/*.jar
      - professeur-service/target/*.jar
      - cours-service/target/*.jar
      - emploi-du-temps-service/target/*.jar
    expire_in: 1 week

unit_tests_backend:
  stage: unit-tests
  image: maven:3.9-openjdk-22  # Changement ici
  script:
    - cd etudiant-service && mvn test
    - cd professeur-service && mvn test
    - cd cours-service && mvn test
    - cd emploi-du-temps-service && mvn test