CREATE TABLE cours (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       titre VARCHAR(255) NOT NULL,
                       professeur_id BIGINT NOT NULL
);