CREATE TABLE emploi_du_temps (
                                 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 cours_id BIGINT NOT NULL,
                                 debut TIMESTAMP NOT NULL,
                                 fin TIMESTAMP NOT NULL
);