name: CI Backend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout du code
      - uses: actions/checkout@v3

      # Configuration de Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Configuration de Maven
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.9

      # Build et tests avec vérification
      - name: Build and Test
        run: |
          for service in etudiant-service professeur-service cours-service emploi-du-temps-service; do
            if [ -d "$service" ]; then
              echo "Processing $service..."
              cd "$service" && mvn clean package -B && mvn test
              cd ..
            else
              echo "Warning: $service not found, skipping..."
            fi
          done