name: CI Backend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.9
      - name: Build and Test
        run: |
          for service in etudiant-service professeur-service cours-service emploi-du-temps-service; do
            if [ -d "$service" ]; then
              echo "Processing $service..."
              cd "$service" && mvn clean package -B && mvn test
              cd ..
            else
              echo "Warning: $service not found, skipping..."
            fi
          done
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: "nourad23"
          password: "Texaco@10"
      - name: Build and Push Docker Images
        run: |
          for service in etudiant-service professeur-service cours-service emploi-du-temps-service; do
            if [ -d "$service" ]; then
              echo "Building and pushing $service..."
              cd "$service" && docker build -t nouradine04/$service:latest . && docker push nouradine04/$service:latest
              cd ..
            fi
          done
      - name: SonarCloud Scan
        run: |
          for service in etudiant-service professeur-service cours-service emploi-du-temps-service; do
            if [ -d "$service" ]; then
              echo "Scanning $service with SonarQube..."
              cd "$service" && mvn sonar:sonar \
                -Dsonar.projectKey=Microservice \
                -Dsonar.host.url=http://localhost:9000 \
                -Dsonar.login=sqp_734b68bdee995314304afc64aa778905487659ea
              cd ..
            fi
          done
